config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments
      member do
        put "like", to: "comments#upvote"
        put "dislike", to: "comments#downvote"
      end
  end
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :user_id, presence: true
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  acts_as_votable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments, through: :posts
  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :last_name])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to @post
    else
      redirect_to @post
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to @post
  end

  def upvote
    @post = Post.find(params[:id])
    #@comment = @post.comments.find(params[:id])
    #@comment.upvote_from current_user
    @post.upvote_from current_user
    redirect_to @post
  end

  def downvote
    @post = Post.find(params[:id])
    @post.downvote_from current_user
    redirect_to @post
  end

private

  def comment_params
    params.require(:comment).permit(:text, :user_id, :username)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order('created_at DESC')
    #@posts = Post.all.includes(:comments) <-- had this originally not sure why
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      redirect_to @post
    else
      render :new
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:success] = "Post was successfully updated!"
      redirect_to @post
    else
      flash[:error] = 'Post was not updated.'
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path, notice: "Post was successfully deleted!"
  end

  def downvote
    #@post = Post.find(params[:id])
    #@comment = @post.comments.find(params[:id])
    #@comment.downvote_from current_user
    #redirect_to @post
  end

  private

    def post_params
      params.require(:post).permit(:title, :body, :category)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<%= form_for [@post, @post.comments.new] do |f| %>
  <%= f.text_area :text %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Queryfriend</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<%= form_for @post do |f| %>
  <%= f.label :title %></br>
  <%= f.text_field :title %></br>
  <%= f.label :category %></br>
  <%= f.select :category, ['Looking For Recommendation','Asking A Question'], prompt: 'Select One' %></br>
  <%= f.label :body %></br>
  <%= f.text_area :body %></br>
  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<%= render :partial => 'post' %>

<%= link_to "Cancel", post_path %>

app/views/posts/index.html.erb
<div class="container">

<h1>Ask A Friend!</h1>

<br />

<div>
  <% if user_signed_in? %>
  Welcome back <%= current_user.username %>
  <% end %>

</div>

<div>

  <% if user_signed_in? %>
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
    <%= link_to "Sign in", new_user_session_path %>
    <%= link_to "Sign Up", new_user_registration_path %>
    <% end %>

</br>
</div>
</br>
<div>
  <% if user_signed_in? %>
  <%= link_to "Submit A Question", new_post_path %>
  <% else %>
  <p><%="Please Sign Up or Sign In to Submit a question." %></p>

  <%end %>


  </p>
</div>

</br>
<div>
  <table class="table table-striped">
    <tbody>
    <% @posts.each do |f| %>
    <tr>
      <td>
      <%= link_to "#{f.title}", post_path(f) %>
      <%= f.created_at.strftime("%B %d, %Y") %>
      </td>
    </tr>
    <% end %>
    </tbody>
  </table>
</div>


</div>

app/views/posts/new.html.erb
<h2>Ask your friends for recommendations or a question</h2>
<%= render :partial => 'post' %>
<%= link_to "Cancel", root_path %>

app/views/posts/show.html.erb
<div class="container">


<p>Title: <%= @post.title %></p></br>
<p>Category: <%= @post.category %></p></br>
<p>Body: <%= @post.body %></p></br>
<p>Date Created: <%= @post.created_at.strftime("%B %d, %Y") %></p></br>

<%= link_to 'Home', root_path %>
<%= link_to 'Edit', edit_post_path(@post) %>
<%= link_to 'Delete', @post, method: :delete, data: {confirm: "Are you sure you want to delete #{@post.title}?"} %>

<% if user_signed_in?  %>
<%= render :partial => "comments/comment" %>
<% else %>
<%= "Please sign up or sign in to leave a comment." %>
<% end %>
</div>

<br />
<div class="container">
  <table class="table table-striped">
    <tbody>
      <% @post.comments.each do |f| %>
        <tr>
          <td>
            <%= link_to like_post_path(@post), class: "like", method: :put do %>
            <i class="fa fa-arrow-up"></i>
            <% end %>
            <br />
            <%= link_to dislike_post_path(@post), class: "dislike" ,method: :put do %>
            <i class='fa fa-arrow-down'></i>
            <% end %>
            <%= @post.get_upvotes.size %>

          </td>
          <td><%= f.text %></td>
          <td><%= f.try(:user).try(:username) %></td>
          <td><%= f.created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  </div>

  <!-- <div>
    <%=  @comment.try(:user).try(:username) %>
  </div> -->